<jsig> ::= <line> | <line> <jsig>
<line> ::=
    <opt-whitespace> <text> ":=" <type-signature> |
    "type" <opt-whitespace> <type-name> ":=" <type-signature>

<opt-whitespace> ::= " " <opt-whitespace> | ""
<type-signature> ::= "(" <argument-list> ") =>" <type-signature> | <type>
<type-name> := <text> | <text> "<" <type> ">"

<argument-list> ::=
    "" |
    <argument> |
    <argument> "," <opt-whitespace> <argument-list>
<type> := <type-name> |
    "{" <key-value-list> "}" |
    '"' <text> '"' |
    <type> "|" <type-signature>

<argument> := <type> | <text> ":" <opt-whitespace> <type>
<key-value-list> := <key-value> | <key-value> "," <key-value-list>
<key-value> := <key> ":" <opt-whitespace> <type-signature>
<key> := <text> | <text> "?" | <text> "!"
